"""
Django settings for bookFlight project.

Generated by 'django-admin startproject' using Django 3.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d79&zmj3-46vuv8db2(u51r*$5^(f74a20k%5t3ms77ygm2hkc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'booking',
    'django_daraja',
    'booking.apps.BookingConfig',
    'rest_framework',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bookFlight.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'booking.context_processors.booking'
            ],
        },
    },
]

WSGI_APPLICATION = 'bookFlight.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / 'staticfiles/'
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
BOOKING_SESSION_ID = 'bookings'


EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'reubensleeq@gmail.com'
EMAIL_HOST_PASSWORD = 'buthvchgracmqaam'
EMAIL_PORT = 587
EMAIL_USE_TLS = True


MPESA_ENVIRONMENT = 'sandbox'
MPESA_CONSUMER_KEY = 'pGjKwt2KESaYGPPpDxhANXUXSXByMdyF'
MPESA_CONSUMER_SECRET = 'P6FN95DkuPSVm56g'
MPESA_SHORTCODE = '600247'
MPESA_EXPRESS_SHORTCODE = '174379'
MPESA_SHORTCODE_TYPE = 'paybill'
MPESA_PASSKEY = 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
MPESA_INITIATOR_USERNAME = 'BlueAirlines'
MPESA_INITIATOR_SECURITY_CREDENTIAL = 'HatyPs6/MD8upXjMM6ne+ra5rLCxqDNSZNaDipTs8C/R8eGh3ELxWf1mkxbWqRmRPH3OB+sjYk7+t9CgYhUlB0tLRmZ2EXKfzu06h6WUxdbBm5eme2P548RFnizBpwk+1G0g0Ftse+Z+X+BnXwvGHEKgI00DsOE4Ex4UTPVpJaEShK7mEMow7TDc43EqUkTtodxXFHYgdY0cpOgtnFQdjRUdER8KUPbNliCbY1S58oAjkHVFU2kjVF8HWplrv/pXVPc2I40L+xbanwrHxxYFW3RGGnwmNr57thXdvFpYDOPI2OxEs40P4NEGISuLeo8bIR+R4aQq7l6ri4kkVa+QpA=='
