# Generated by Django 4.2.3 on 2023-07-23 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_aeroplane_capacity_remove_flight_schedule_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flight",
            old_name="schedule",
            new_name="schedules",
        ),
    ]
