# Generated by Django 4.2.3 on 2023-07-23 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_alter_booking_flight"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="booking",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="booking",
            name="type_of_trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="booking.typeoftrip",
            ),
        ),
    ]
