# Generated by Django 4.2.3 on 2023-07-23 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_booking_cost_booking_paid_alter_booking_type_of_trip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="type_of_trip",
        ),
        migrations.AddField(
            model_name="flight",
            name="type_of_trip",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flights",
                to="booking.typeoftrip",
            ),
            preserve_default=False,
        ),
    ]
