# Generated by Django 4.2.3 on 2023-07-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_remove_booking_type_of_trip_flight_type_of_trip"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sits",
            new_name="Sit",
        ),
        migrations.RenameIndex(
            model_name="sit",
            new_name="booking_sit_sit_no_6413b5_idx",
            old_name="booking_sit_sit_no_0d05bc_idx",
        ),
    ]
