# Generated by Django 4.2.3 on 2023-07-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0008_rename_sit_seat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aeroplane",
            name="number_plate",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
