# Generated by Django 4.2.3 on 2023-07-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_alter_aeroplane_number_plate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Time",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dep_time", models.TimeField()),
                ("arrival_time", models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="arrival_time",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="dep_time",
        ),
        migrations.AddField(
            model_name="schedule",
            name="time",
            field=models.ManyToManyField(related_name="schedules", to="booking.time"),
        ),
    ]
