# Generated by Django 4.2.3 on 2023-07-24 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0010_time_remove_schedule_arrival_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="flight_class",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="booking.flightclass",
            ),
            preserve_default=False,
        ),
    ]
