# Generated by Django 4.2.3 on 2023-07-24 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0011_flight_flight_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="flight_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flights",
                to="booking.flightclass",
            ),
        ),
    ]
