# Generated by Django 4.2.3 on 2023-07-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0012_alter_flight_flight_class"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seat",
            options={"ordering": ["seat_no"]},
        ),
        migrations.RemoveIndex(
            model_name="seat",
            name="booking_sea_sit_no_424782_idx",
        ),
        migrations.RenameField(
            model_name="seat",
            old_name="sit_no",
            new_name="seat_no",
        ),
        migrations.RemoveField(
            model_name="seat",
            name="aeroplane",
        ),
        migrations.AddField(
            model_name="aeroplane",
            name="aeroplane",
            field=models.ManyToManyField(related_name="sits", to="booking.seat"),
        ),
        migrations.AddIndex(
            model_name="seat",
            index=models.Index(
                fields=["seat_no"], name="booking_sea_seat_no_854dde_idx"
            ),
        ),
    ]
