# Generated by Django 4.2.3 on 2023-07-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0013_alter_seat_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aeroplane",
            old_name="aeroplane",
            new_name="seat",
        ),
    ]
