# Generated by Django 4.2.3 on 2023-07-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0014_rename_aeroplane_aeroplane_seat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="flight_class",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="price",
        ),
        migrations.AddField(
            model_name="seat",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aeroplane",
            name="seat",
            field=models.ManyToManyField(related_name="aeroplane", to="booking.seat"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="schedules",
            field=models.ManyToManyField(related_name="flights", to="booking.schedule"),
        ),
    ]
