# Generated by Django 4.2.3 on 2023-07-27 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0015_remove_flight_flight_class_remove_flight_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="type_of_trip",
        ),
        migrations.AddField(
            model_name="booking",
            name="type_of_trip",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flights",
                to="booking.typeoftrip",
            ),
            preserve_default=False,
        ),
    ]
