# Generated by Django 4.2.3 on 2023-07-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0016_remove_flight_type_of_trip_booking_type_of_trip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aeroplane",
            name="seat",
        ),
        migrations.AddField(
            model_name="aeroplane",
            name="seats",
            field=models.ManyToManyField(related_name="aeroplanes", to="booking.seat"),
        ),
    ]
