# Generated by Django 4.2.3 on 2023-07-27 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0017_remove_aeroplane_seat_aeroplane_seats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seat",
            name="price",
        ),
        migrations.AddField(
            model_name="flight",
            name="flight_class",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flights",
                to="booking.flightclass",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flight",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
