# Generated by Django 4.2.3 on 2023-07-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0020_remove_aeroplane_seats_seat_aeroplane"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seat",
            name="seat_no",
            field=models.CharField(max_length=6),
        ),
    ]
