# Generated by Django 4.2.3 on 2023-07-29 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0022_alter_aeroplane_options_alter_time_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seat",
            name="flight_class",
        ),
        migrations.AddField(
            model_name="seat",
            name="seat_class",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="seats",
                to="booking.flightclass",
            ),
            preserve_default=False,
        ),
    ]
