# Generated by Django 4.2.3 on 2023-07-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0023_remove_seat_flight_class_seat_seat_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="seat_no",
            field=models.ManyToManyField(related_name="bookings", to="booking.seat"),
        ),
    ]
