# Generated by Django 4.2.3 on 2023-07-29 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0024_booking_seat_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="aeroplane",
        ),
        migrations.AddField(
            model_name="time",
            name="aeroplane",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="times",
                to="booking.aeroplane",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booking",
            name="seat_no",
            field=models.ManyToManyField(
                default=None, related_name="bookings", to="booking.seat"
            ),
        ),
    ]
