# Generated by Django 4.2.3 on 2023-07-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "booking",
            "0026_rename_flightclass_seatclass_remove_flight_schedules_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flight",
            options={"verbose_name_plural": "Flights"},
        ),
        migrations.AlterModelOptions(
            name="schedule",
            options={"verbose_name_plural": "Schedules"},
        ),
        migrations.RemoveField(
            model_name="time",
            name="aeroplane",
        ),
        migrations.AddField(
            model_name="time",
            name="aeroplanes",
            field=models.ManyToManyField(related_name="times", to="booking.aeroplane"),
        ),
        migrations.AddIndex(
            model_name="flight",
            index=models.Index(fields=["origin"], name="booking_fli_origin_fb2f3c_idx"),
        ),
    ]
