# Generated by Django 4.2.3 on 2023-07-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0027_alter_flight_options_alter_schedule_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Flight",
            new_name="Route",
        ),
        migrations.RenameField(
            model_name="aeroplane",
            old_name="flight",
            new_name="route",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="flight",
            new_name="route",
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="flights",
            new_name="routes",
        ),
        migrations.RenameIndex(
            model_name="route",
            new_name="booking_rou_origin_96895c_idx",
            old_name="booking_fli_origin_fb2f3c_idx",
        ),
    ]
