# Generated by Django 4.2.3 on 2023-08-11 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0029_rename_password_id_passenger_passport_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="arrival_date",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(
                        models.DateField(),
                        "Arrivale date must not be before departure date",
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="time",
            name="arrival_time",
            field=models.TimeField(
                validators=[
                    django.core.validators.MinValueValidator(
                        models.TimeField(), "Arrival time must not be depature time"
                    )
                ]
            ),
        ),
    ]
